# Generated by Django 3.0.8 on 2022-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
