# Generated by Django 3.0.8 on 2022-01-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('model_no', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BI', 'Bike'), ('CY', 'Cycle'), ('CA', 'Car'), ('BO', 'Boat')], max_length=2)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
